export default {
  INCRE_ITEM_COUNT: 'INCRE_ITEM_COUNT',
  LOGIN: 'LOGIN',
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  CLOSE_BUNDLE_DIALOG: 'CLOSE_BUNDLE_DIALOG',
  CLOSE_PROJ_DIALOG: 'CLOSE_PROJ_DIALOG',
  OPEN_BUNDLE_DIALOG: 'OPEN_BUNDLE_DIALOG',
  OPEN_PROJ_DIALOG: 'OPEN_PROJ_DIALOG',
  RECEIVE_PROJECT: 'RECEIVE_PROJECT',
  RECEIVE_PROJECT_ITEM: 'RECEIVE_PROJECT_ITEM',
  RECEIVE_THREAD: 'RECEIVE_THREAD',
  RECEIVE_TAG: 'RECEIVE_TAG',
  SORT_THREADS: 'SORT_THREADS',
  UPDATE_TAG: 'UPDATE_TAG',
  UPDATE_THREAD: 'UPDATE_THREAD'
}
