export default {
  LOGIN: 'LOGIN',
  LOCATION_CHANGE: '@@router/LOCATION_CHANGE',
  RECEIVE_PROJECT_ITEMS: 'RECEIVE_PROJECT_ITEMS',
  RECEIVE_THREAD: 'RECEIVE_THREAD',
  RECEIVE_TAG: 'RECEIVE_TAG',
  SORT_THREADS: 'SORT_THREADS',
  UPDATE_TAG: 'UPDATE_TAG',
  UPDATE_THREAD: 'UPDATE_THREAD'
}
